version: '3.8'

services:

  redis:
    image: redis
    restart: always
    container_name: 'demo_app_redis'
    command: redis-server
    ports:
      - '6379:6379'

  web:
    build: .
    restart: always
    container_name: 'demo_app_django'
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  celery:
    build: .
    container_name: 'demo_app_upf'
    command: celery -A core worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
