version: '3.8'

services:

  redis:
      image: redis:5.0.1
      hostname: redis
      ports:
        - "6379:6379"

  worker:
      build:
        context: .
      hostname: worker
      command:  python3 -m celery -A uploading_processing worker -l debug
      volumes:
        - ./service:/service
      links:
        - redis
      depends_on:
        - web
        - redis

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
